import 'package:flutter/material.dart';
import 'package:flutter_html/flutter_html.dart';

class News extends StatefulWidget {
  @override
  _NewsState createState() => _NewsState();
}

class _NewsState extends State<News> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          backgroundColor: Colors.green, title: Center(child: Text("News"))),
      body: SingleChildScrollView(
        child: Html(
          data:
              ''' <h1 class="main-content__title " data-anchor="Introduction" style="margin: 0px 0px 2px; font-family: noto_serifregular, serif; font-weight: 300; line-height: 1rem; transition: font-size 0.3s ease 0s; font-size: 3.125rem; padding: 2rem 0px 0px; border: 0px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(0, 44, 119); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">What Is Coronavirus?</h1>
<nav aria-label="Tag Links" class="tags " style="font-family: noto_sansregular, sans-serif, sans-serif; font-size: 16px; margin: 0px 0px 1.875rem; padding: 0px; border-width: 1px 0px; border-style: solid; border-color: rgba(190, 185, 166, 0.29); border-image: initial; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; display: block; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a class="tag" href="https://www.hopkinsmedicine.org/health/infectious-diseases" style="text-decoration: none; color: rgb(0, 109, 199); font-family: noto_sansregular, sans-serif; font-size: 0.875rem; line-height: 1.875rem; display: inline-block; margin-right: 10px; transition: color 0.4s ease-out 0s;">Infectious Diseases</a></nav>
<div class="rtf " style="margin: 0px; padding: 0px; border: 0px; font-size: 16px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51); font-family: noto_sansregular, sans-serif, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;">Coronaviruses are a type of virus. There are many different kinds, and some cause disease. A coronavirus identified in 2019, SARS-CoV-2, has caused a pandemic of respiratory illness, called COVID-19.</p>
</div>
<div class="rtf " style="margin: 0px; padding: 0px; border: 0px; font-size: 16px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51); font-family: noto_sansregular, sans-serif, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;"><span style="margin: 0px; padding: 0px; border: 0px; font-size: 2.313rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51); font-family: noto_serifregular, serif;">How does the coronavirus spread?</span></p>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;">As of now, researchers know that the coronavirus is spread through droplets and virus particles released into the air when an infected person breathes, talks, laughs, sings, coughs or sneezes. Larger droplets may fall to the ground in a few seconds, but tiny infectious particles can linger in the air and accumulate in indoor places, especially where many people are gathered and there is poor ventilation. This is why mask-wearing, hand hygiene and physical distancing are essential to preventing COVID-19.</p>
    <h2 style="margin: 4.375rem 0px 2.5rem; font-family: noto_serifregular, serif; font-weight: 400; line-height: 2.75rem; transition: font-size 0.3s ease 0s; font-size: 2.313rem; padding: 0px; border: 0px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51);">How did the coronavirus start?</h2>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;">The first case of COVID-19 was reported Dec. 1, 2019, and the cause was a then-new coronavirus later named SARS-CoV-2. SARS-CoV-2 may have originated in an animal and changed (mutated) so it could cause illness in humans. In the past, several infectious disease outbreaks have been traced to viruses originating in birds, pigs, bats and other animals that mutated to become dangerous to humans. Research continues, and more study may reveal how and why the coronavirus evolved to cause pandemic disease.</p>
    <h2 style="margin: 4.375rem 0px 2.5rem; font-family: noto_serifregular, serif; font-weight: 400; line-height: 2.75rem; transition: font-size 0.3s ease 0s; font-size: 2.313rem; padding: 0px; border: 0px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51);">What is the incubation period for COVID-19?</h2>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;">Symptoms show up in people within two to 14 days of exposure to the virus. A person infected with the coronavirus is contagious to others for up to two days before symptoms appear, and they remain contagious to others for 10 to 20 days, depending upon their immune system and the severity of their illness.&nbsp;</p>
</div>
<div class="rtf " style="margin: 0px; padding: 0px; border: 0px; font-size: 16px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51); font-family: noto_sansregular, sans-serif, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <h4 data-anchor="What have you learned about coronavirus in the last six months?" style="margin: 3.5rem 0px 1.5rem; font-family: noto_sansregular, sans-serif; font-weight: 700; line-height: 1.563rem; transition: font-size 0.3s ease 0s; font-size: 1.313rem; padding: 0px; border: 0px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51);">What have you learned about coronavirus in the last six months?</h4>
    <div class="video full" style="margin: 3rem 0px 0px; padding: 1rem; border: 0px; font-size: 16px; vertical-align: baseline; background: white; text-size-adjust: none; box-sizing: border-box; box-shadow: rgba(1, 0, 0, 0.2) 0px 0px 9.5px 0.5px;">
        <div class="video__wrap" style="margin: 0px; padding: 0px 0px 34.875px; border: 0px; font-size: 16px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; cursor: pointer; position: relative; width: 622px; height: 0px;"><iframe title="Video: What have you learned about coronavirus in the last six months?" src="https://www.youtube.com/embed/g7ilXCHld7g?rel=0&showinfo=0" allowfullscreen="" style="margin: 0px; padding: 0px; border: 0px; font-size: 16px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; display: block; width: 622px; height: 349.875px; max-width: 100%; position: absolute; top: 0px; left: 0px; z-index: 1;"></iframe></div>
        <div class="video__desc" style="margin: 0px; padding: 1rem; border: 0px; font-size: 0.875em; vertical-align: baseline; background: rgba(169, 163, 155, 0.2); text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.438em; color: black;">Infectious disease expert Lisa Maragakis explains the advances in COVID-19 treatments and how knowledge of COVID-19 can assist in preventing further spread of the virus.</div>
    </div>
</div>
<div class="rtf " style="margin: 0px; padding: 0px; border: 0px; font-size: 16px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51); font-family: noto_sansregular, sans-serif, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <h2 style="margin: 4.375rem 0px 2.5rem; font-family: noto_serifregular, serif; font-weight: 400; line-height: 2.75rem; transition: font-size 0.3s ease 0s; font-size: 2.313rem; padding: 0px; border: 0px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51);">What are symptoms of coronavirus?</h2>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;">COVID-19 symptoms include:</p>
    <ul style="margin: 0px 0px 1rem; padding: 0px 0px 0px 1.5rem; border: 0px; font-size: 16px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none;">
        <li style="margin: 0px 0px 1.5rem; padding: 0px 0px 0px 2rem; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none; position: relative; line-height: 1.688rem;">Cough</li>
        <li style="margin: 0px 0px 1.5rem; padding: 0px 0px 0px 2rem; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none; position: relative; line-height: 1.688rem;">Fever or chills</li>
        <li style="margin: 0px 0px 1.5rem; padding: 0px 0px 0px 2rem; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none; position: relative; line-height: 1.688rem;">Shortness of breath or difficulty breathing</li>
        <li style="margin: 0px 0px 1.5rem; padding: 0px 0px 0px 2rem; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none; position: relative; line-height: 1.688rem;">Muscle or body aches</li>
        <li style="margin: 0px 0px 1.5rem; padding: 0px 0px 0px 2rem; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none; position: relative; line-height: 1.688rem;">Sore throat</li>
        <li style="margin: 0px 0px 1.5rem; padding: 0px 0px 0px 2rem; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none; position: relative; line-height: 1.688rem;">New loss of taste or smell</li>
        <li style="margin: 0px 0px 1.5rem; padding: 0px 0px 0px 2rem; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none; position: relative; line-height: 1.688rem;">Diarrhea</li>
        <li style="margin: 0px 0px 1.5rem; padding: 0px 0px 0px 2rem; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none; position: relative; line-height: 1.688rem;">Headache</li>
        <li style="margin: 0px 0px 1.5rem; padding: 0px 0px 0px 2rem; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none; position: relative; line-height: 1.688rem;">New fatigue</li>
        <li style="margin: 0px 0px 1.5rem; padding: 0px 0px 0px 2rem; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none; position: relative; line-height: 1.688rem;">Nausea or vomiting</li>
        <li style="margin: 0px 0px 1.5rem; padding: 0px 0px 0px 2rem; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none; position: relative; line-height: 1.688rem;">Congestion or runny nose</li>
    </ul>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;">Some people infected with the coronavirus have mild COVID-19 illness, and others have no symptoms at all. In some cases, however, COVID-19 can lead to respiratory failure, lasting <a href="https://www.hopkinsmedicine.org/health/conditions-and-diseases/coronavirus/what-coronavirus-does-to-the-lungs" style="text-decoration: none; color: rgb(0, 109, 199); transition: color 0.4s ease-out 0s;">lung</a> and <a href="https://www.hopkinsmedicine.org/health/conditions-and-diseases/coronavirus/can-coronavirus-cause-heart-damage" style="text-decoration: none; color: rgb(0, 109, 199); transition: color 0.4s ease-out 0s;">heart muscle damage</a>, <a href="https://www.hopkinsmedicine.org/health/conditions-and-diseases/coronavirus/how-does-coronavirus-affect-the-brain" style="text-decoration: none; color: rgb(0, 109, 199); transition: color 0.4s ease-out 0s;">nervous system problems</a>, <a href="https://www.hopkinsmedicine.org/health/conditions-and-diseases/coronavirus/coronavirus-kidney-damage-caused-by-covid19" style="text-decoration: none; color: rgb(0, 109, 199); transition: color 0.4s ease-out 0s;">kidney failure</a> or death.</p>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;">If you have a fever or any of the symptoms listed above, call your doctor or a health care provider and explain your symptoms over the phone before going to the doctor&rsquo;s office, urgent care facility or emergency room. Here are suggestions <a href="https://www.hopkinsmedicine.org/health/conditions-and-diseases/coronavirus/coronavirus-what-if-i-feel-sick" style="text-decoration: none; color: rgb(0, 109, 199); transition: color 0.4s ease-out 0s;">if you feel sick and are concerned you might have COVID-19</a>.</p>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;"><br></p>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;"><a href="https://www.hopkinsmedicine.org/health/conditions-and-diseases/coronavirus/coronavirus-symptoms-frequently-asked-questions" style="text-decoration: none; color: rgb(0, 109, 199); transition: color 0.4s ease-out 0s;">Learn more about COVID-19 symptoms</a>.</p>
</div>
<div class="rtf " style="margin: 0px; padding: 0px; border: 0px; font-size: 16px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51); font-family: noto_sansregular, sans-serif, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <h4 data-anchor="What Is Coronavirus?" style="margin: 3.5rem 0px 1.5rem; font-family: noto_sansregular, sans-serif; font-weight: 700; line-height: 1.563rem; transition: font-size 0.3s ease 0s; font-size: 1.313rem; padding: 0px; border: 0px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51);">What Is Coronavirus?</h4>
    <div class="video full" style="margin: 3rem 0px 0px; padding: 1rem; border: 0px; font-size: 16px; vertical-align: baseline; background: white; text-size-adjust: none; box-sizing: border-box; box-shadow: rgba(1, 0, 0, 0.2) 0px 0px 9.5px 0.5px;">
        <div class="video__wrap" style="margin: 0px; padding: 0px 0px 34.875px; border: 0px; font-size: 16px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; cursor: pointer; position: relative; width: 622px; height: 0px;"><iframe title="Video: What Is Coronavirus?" src="https://www.youtube.com/embed/sHP0UIdZyI4?rel=0&showinfo=0" allowfullscreen="" style="margin: 0px; padding: 0px; border: 0px; font-size: 16px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; display: block; width: 622px; height: 349.875px; max-width: 100%; position: absolute; top: 0px; left: 0px; z-index: 1;"></iframe></div>
    </div>
</div>
<div class="rtf " style="margin: 0px; padding: 0px; border: 0px; font-size: 16px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51); font-family: noto_sansregular, sans-serif, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <h2 style="margin: 4.375rem 0px 2.5rem; font-family: noto_serifregular, serif; font-weight: 400; line-height: 2.75rem; transition: font-size 0.3s ease 0s; font-size: 2.313rem; padding: 0px; border: 0px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51);">How is COVID-19 diagnosed?</h2>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;">COVID-19 is diagnosed through a laboratory test. Diagnosis by examination alone is difficult since many COVID-19 signs and symptoms can be caused by other illnesses. Some people with the coronavirus do not have symptoms at all. <a href="https://www.hopkinsmedicine.org/health/conditions-and-diseases/coronavirus/coronavirus-test-what-you-need-to-know" style="text-decoration: none; color: rgb(0, 109, 199); transition: color 0.4s ease-out 0s;">Learn more about COVID-19 testing</a>.</p>
    <h2 style="margin: 4.375rem 0px 2.5rem; font-family: noto_serifregular, serif; font-weight: 400; line-height: 2.75rem; transition: font-size 0.3s ease 0s; font-size: 2.313rem; padding: 0px; border: 0px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51);">How is COVID-19 treated?</h2>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;">Treatment for COVID-19 addresses the signs and symptoms of the infection and supports people with more severe disease. For mild cases of coronavirus disease, your doctor may recommend measures such as fever reducers or over-the-counter medications. More severe cases may require hospital care, where a patient may receive a combination of treatments that could include steroids, oxygen, mechanical breathing support and other <a href="https://www.hopkinsmedicine.org/health/conditions-and-diseases/coronavirus/coronavirus-treatment-whats-in-development" style="text-decoration: none; color: rgb(0, 109, 199); transition: color 0.4s ease-out 0s;">COVID-19 treatments in development.</a> Infusions of monoclonal antibodies given to certain patients early in the infection may reduce the symptoms, severity and duration of the illness.</p>
    <h2 style="margin: 4.375rem 0px 2.5rem; font-family: noto_serifregular, serif; font-weight: 400; line-height: 2.75rem; transition: font-size 0.3s ease 0s; font-size: 2.313rem; padding: 0px; border: 0px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51);">How do you protect yourself from this coronavirus?</h2>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;">Vaccines are now authorized to prevent infection with SARS-CoV-2, the coronavirus that causes COVID-19. But until more is understood about how the vaccines affect a person&rsquo;s ability to transmit the virus, precautions such as mask-wearing, physical distancing and hand hygiene should continue regardless of a person&rsquo;s vaccination status to help <a href="https://www.hopkinsmedicine.org/coronavirus/covid-19-vaccine/" style="text-decoration: none; color: rgb(0, 109, 199); transition: color 0.4s ease-out 0s;">prevent</a> the spread of COVID-19. Learn more about the COVID-19 vaccine and <a href="https://www.hopkinsmedicine.org/health/conditions-and-diseases/coronavirus/how-can-i-protect-myself-from-coronavirus" style="text-decoration: none; color: rgb(0, 109, 199); transition: color 0.4s ease-out 0s;">ways to protect yourself</a>.</p>
    <h2 style="margin: 4.375rem 0px 2.5rem; font-family: noto_serifregular, serif; font-weight: 400; line-height: 2.75rem; transition: font-size 0.3s ease 0s; font-size: 2.313rem; padding: 0px; border: 0px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51);">Does COVID-19 cause death?</h2>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;">Yes, severe COVID-19 can be fatal. For updates of coronavirus infections, deaths and vaccinations worldwide, see the <a href="https://www.arcgis.com/apps/dashboards/bda7594740fd40299423467b48e9ecf6" style="text-decoration: none; color: rgb(0, 109, 199); transition: color 0.4s ease-out 0s;" target="_blank">Coronavirus COVID-19 Global Cases</a> map developed by the Johns Hopkins Center for Systems Science and Engineering.</p>
</div>
<div class="rtf " style="margin: 0px; padding: 0px; border: 0px; font-size: 16px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51); font-family: noto_sansregular, sans-serif, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <h2 style="margin: 4.375rem 0px 2.5rem; font-family: noto_serifregular, serif; font-weight: 400; line-height: 2.75rem; transition: font-size 0.3s ease 0s; font-size: 2.313rem; padding: 0px; border: 0px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51);">Why is it called coronavirus?</h2>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;">Coronaviruses are named for their appearance: &ldquo;corona&rdquo; means &ldquo;crown.&rdquo; The virus&rsquo;s outer layers are covered with spike proteins that surround them like a crown.</p>
    <h2 style="margin: 4.375rem 0px 2.5rem; font-family: noto_serifregular, serif; font-weight: 400; line-height: 2.75rem; transition: font-size 0.3s ease 0s; font-size: 2.313rem; padding: 0px; border: 0px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51);">Is this coronavirus different from SARS?</h2>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;"><a href="https://www.hopkinsmedicine.org/health/conditions-and-diseases/severe-acute-respiratory-syndrome-sars" style="text-decoration: none; color: rgb(0, 109, 199); transition: color 0.4s ease-out 0s;">SARS</a> stands for severe acute respiratory syndrome. In 2003, an outbreak of SARS affected people in several countries before ending in 2004. The coronavirus that causes COVID-19 is similar to the one that caused the 2003 SARS outbreak.</p>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;">Since the 2019 coronavirus is related to the original coronavirus that caused SARS and can also cause severe acute respiratory syndrome, there is &ldquo;SARS&rdquo; in its name: SARS-CoV-2. Much is still unknown about these viruses, but SARS-CoV-2 spreads faster and farther than the 2003 SARS-CoV-1 virus. This is likely because of how easily it is transmitted person to person, even from asymptomatic carriers of the virus.</p>
    <h2 style="margin: 4.375rem 0px 2.5rem; font-family: noto_serifregular, serif; font-weight: 400; line-height: 2.75rem; transition: font-size 0.3s ease 0s; font-size: 2.313rem; padding: 0px; border: 0px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51);">Are there different variants of this coronavirus?</h2>
    <p style="margin: 0px 0px 2rem; padding: 0px; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; font-family: noto_sansregular, sans-serif; line-height: 1.688rem; color: black;">Yes, there are different variants of this coronavirus. Like other viruses, the coronavirus that causes COVID-19 can change (mutate). In December 2020, B.1.1.7, a new variant, was identified in the United Kingdom, and since then, variants have appeared in other locations around the world, including B.1.351, first isolated in South Africa, and others. Mutations may enable the coronavirus to spread faster from person to person, and may cause more severe disease. More infections can result in more people getting very sick and also create more opportunity for the virus to develop further mutations. Read more about <a href="https://www.hopkinsmedicine.org/health/conditions-and-diseases/coronavirus/a-new-strain-of-coronavirus-what-you-should-know" style="text-decoration: none; color: rgb(0, 109, 199); transition: color 0.4s ease-out 0s;">coronavirus variants</a>.</p>
</div>
<div class="rtf " style="margin: 0px; padding: 0px; border: 0px; font-size: 16px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51); font-family: noto_sansregular, sans-serif, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <h4 data-anchor="Coronavirus: What do I do if I Feel Sick?" style="margin: 3.5rem 0px 1.5rem; font-family: noto_sansregular, sans-serif; font-weight: 700; line-height: 1.563rem; transition: font-size 0.3s ease 0s; font-size: 1.313rem; padding: 0px; border: 0px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51);">Coronavirus: What do I do if I Feel Sick?</h4>
</div>
<div class="rtf " style="margin: 0px; padding: 0px; border: 0px; font-size: 16px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51); font-family: noto_sansregular, sans-serif, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <h2 style="margin: 4.375rem 0px 2.5rem; font-family: noto_serifregular, serif; font-weight: 400; line-height: 2.75rem; transition: font-size 0.3s ease 0s; font-size: 2.313rem; padding: 0px; border: 0px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; color: rgb(51, 51, 51);">About Coronaviruses</h2>
    <ul style="margin: 0px 0px 1rem; padding: 0px 0px 0px 1.5rem; border: 0px; font-size: 16px; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none;">
        <li style="margin: 0px 0px 1.5rem; padding: 0px 0px 0px 2rem; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none; position: relative; line-height: 1.688rem;">Coronaviruses are common in different animals. Rarely, an animal coronavirus can infect humans.</li>
        <li style="margin: 0px 0px 1.5rem; padding: 0px 0px 0px 2rem; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none; position: relative; line-height: 1.688rem;">There are many different kinds of coronaviruses. Some of them can cause colds or other mild respiratory (nose, throat, lung) illnesses.</li>
        <li style="margin: 0px 0px 1.5rem; padding: 0px 0px 0px 2rem; border: 0px; font-size: 1.063rem; vertical-align: baseline; background: transparent; text-size-adjust: none; box-sizing: border-box; list-style: none; position: relative; line-height: 1.688rem;">Other coronaviruses can cause serious diseases, including severe acute respiratory syndrome (SARS) and Middle East respiratory syndrome (MERS).</li>
    </ul>
</div>''',
        ),
      ),
    );
  }
}
