import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:flutter_html/flutter_html.dart';

class FirstAid extends StatefulWidget {
  // var response;
//  FirstAid(this.response);
  @override
  _FirstAidState createState() => _FirstAidState();
}

class _FirstAidState extends State<FirstAid> {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          backgroundColor: Colors.green,
          title: Center(child: Text("First Aid"))),
      body: SingleChildScrollView(
        child: Html(
          data:
              ''' <div class="rpl-above-content" style='background-repeat: no-repeat; background-position: left -4.5rem; background-size: 20rem; color: rgb(34, 34, 34); font-family: "Times New Roman"; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
    <div class="rpl-page-header">
        <div class="rpl-above-content__inner" style="background-repeat: no-repeat; background-position: 50% center; background-size: cover; padding-top: 0px;">
            <div class="rpl-above-content__below">
                <div class="page-header" data-v-1e99a558="" style='position: relative; background-color: rgb(0, 128, 85); background-image: url("");'>
                    <div class="rpl-site-constrain--on-all" style="padding-left: calc(50% - 33rem) !important; padding-right: calc(50% - 33rem) !important;">
                        <div class="page-header__column" style="padding-top: 0px; position: relative;">
                            <div class="page-header__column-inner" style="position: relative; z-index: 1; padding-top: 3.375rem;">
                                <div class="rpl-row page-header__backing" style="margin-left: 0.5rem; margin-right: 0.5rem; width: calc(100% + 1rem); box-sizing: border-box; display: flex; flex-wrap: wrap; -webkit-box-pack: start; justify-content: flex-start; position: relative;">
                                    <div class="rpl-col rpl-col--full rpl-col--8-m" style="width: calc(66.6667% - 1rem); margin-left: 0.5rem; margin-right: 0.5rem; box-sizing: border-box; -webkit-box-flex: 0; flex: 0 0 auto;">
                                        <div class="page-header__mobile-column" style="position: static; margin: 0px; padding-bottom: 0px;">
                                            <div class="page-header__mobile-inner" style="position: static; z-index: 1;">
                                                <h1 class="page-header__title" style='font-size: 2.875rem; margin: 0px; color: rgb(0, 26, 53); line-height: 3.125rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400;'>First aid basics and DRSABCD</h1>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="page-actions-container rpl-col rpl-col--12 rpl-col--3-m rpl-col--push-1-m" style="width: calc(25% - 1rem); margin-left: 0.5rem; margin-right: 0.5rem; box-sizing: border-box; -webkit-box-flex: 0; flex: 0 0 auto; position: relative; left: 89.3281px; display: flex; -webkit-box-pack: end; justify-content: flex-end;">
                                        <h2 class="rpl-visually-hidden" style="position: absolute; width: 1px; height: 1px; padding: 0px; margin: 1px; overflow: hidden; clip: rect(0px, 0px, 0px, 0px); border: 0px; pointer-events: none;">Actions for this page</h2>
                                        <ul class="page-actions rs_preserve rs_skip" style="position: relative; display: flex; -webkit-box-pack: end; justify-content: flex-end; list-style-type: none; margin: 0px 0px 0px auto; padding: 0px; -webkit-box-align: end; align-items: flex-end; min-width: 236px; height: 50px;">
                                            <li class="page-actions__list-item listen-button" style="margin-left: 0px;"><button class="page-actions__button rpl-link" style='font-family: VIC-Regular, Arial, Helvetica, "sans-serif"; font-size: 0.875rem; line-height: 1.25rem; margin: 0px; overflow: visible; text-transform: none; appearance: none; text-decoration: none; background: none rgb(0, 26, 53); border: 0px; padding: 0.375rem 2rem; text-align: center; cursor: pointer; min-width: 4rem; transition: all 0.15s ease-in-out 0s; color: rgb(255, 255, 255); font-weight: 400; border-top-left-radius: 1.125rem; border-bottom-left-radius: 1.125rem;'><span class="page-actions__icon" style="display: inline-block; width: 0.75rem; height: 0.75rem; text-align: center; margin-right: 0.5rem; margin-left: -0.25rem;"><svg aria-hidden="true" class="rpl-icon rpl-icon--microphone rpl-icon--color_white" style="width:6.5px;height:12.35px;">
                                                            <path d="M9 8.01a1 1 0 00-1 1v1.98c0 1.654-1.346 3-3 3s-3-1.346-3-3V9.01a1 1 0 10-2 0v2.068a5.005 5.005 0 005 4.911 5.005 5.005 0 005-4.91V9.01a1 1 0 00-1-1z" transform="translate(0 0.999496)"></path>
                                                            <path d="M3 3.001v7.997a2.002 2.002 0 004.003 0V3.001a2.001 2.001 0 10-4.003 0zM6 17.979a1 1 0 11-2 0 1 1 0 112 0z" transform="translate(0 0.999496)"></path>
                                                        </svg></span>Listen</button></li>
                                            <li class="page-actions__list-item download-button" style="margin-left: 1px;"><button class="page-actions__button rpl-link" style='font-family: VIC-Regular, Arial, Helvetica, "sans-serif"; font-size: 0.875rem; line-height: 1.25rem; margin: 0px; overflow: visible; text-transform: none; appearance: none; text-decoration: none; background: none rgb(0, 26, 53); border: 0px; padding: 0.375rem 2rem; text-align: center; cursor: pointer; min-width: 4rem; transition: all 0.15s ease-in-out 0s; color: rgb(255, 255, 255); font-weight: 400; border-top-right-radius: 1.125rem; border-bottom-right-radius: 1.125rem;'><span class="page-actions__icon" style="display: inline-block; width: 0.75rem; height: 0.75rem; text-align: center; margin-right: 0.5rem; margin-left: -0.25rem;"><svg aria-hidden="true" class="rpl-icon rpl-icon--download rpl-icon--color_white" style="width:8.8px;height:9.600000000000001px;">
                                                            <path d="M9.643 12h-9A.641.641 0 010 11.357v-.643c0-.356.287-.643.643-.643h9c.356 0 .643.287.643.643v.643a.641.641 0 01-.643.643zM3.429.643v3.643h-2.35a.535.535 0 00-.377.913l4.077 4.077c.2.2.53.2.73 0l4.078-4.077a.535.535 0 00-.378-.913H6.857V.643A.641.641 0 006.214 0H4.071a.641.641 0 00-.642.643z"></path>
                                                        </svg></span>Print</button></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="rpl-above-content-two"><br></div>
</div>
<section class="rpl-content" style='padding-top: 4rem; padding-bottom: 6rem; color: rgb(34, 34, 34); font-family: "Times New Roman"; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
    <div class="rpl-site-constrain--on-all" style="padding-left: calc(50% - 33rem) !important; padding-right: calc(50% - 33rem) !important;">
        <div class="rpl-row" style="margin-left: 0.5rem; margin-right: 0.5rem; width: calc(100% + 1rem); box-sizing: border-box; display: flex; flex-wrap: wrap; -webkit-box-pack: start; justify-content: flex-start;">
            <div class="rpl-main rpl-col rpl-col--full" style="width: calc(100% - 1rem); margin-left: 0.5rem; margin-right: 0.5rem; box-sizing: border-box; -webkit-box-flex: 0; flex: 0 0 auto;">
                <div class="rpl-row keyIntro" data-v-1e99a558="" style="margin-left: 0.5rem; margin-right: 0.5rem; width: calc(100% + 1rem); box-sizing: border-box; display: flex; flex-wrap: wrap; -webkit-box-pack: start; justify-content: flex-start; margin-bottom: 3rem;">
                    <div class="rpl-col rpl-col--full rpl-col--8-m" data-v-1e99a558="" style="width: calc(66.6667% - 1rem); margin-left: 0.5rem; margin-right: 0.5rem; box-sizing: border-box; -webkit-box-flex: 0; flex: 0 0 auto;">
                        <div class="content-intro" data-v-1e99a558="" data-v-7796d9ba="" style="padding: 2.5rem 1.875rem; background-color: rgb(243, 244, 246); border-radius: 1.75rem; border: 0px;">
                            <div class="content-intro__header" data-v-7796d9ba="" style="display: flex; -webkit-box-align: baseline; align-items: baseline; margin-bottom: 0.5rem;">
                                <h2 class="content-intro__header-text" data-v-7796d9ba="" style='margin-top: 0px; margin-bottom: 0px; color: rgb(0, 26, 53); font-size: 1.125rem; line-height: 1.375rem; font-family: VIC-Medium, Arial, Helvetica, "sans-serif"; font-weight: 400;'>Summary</h2><a class="read-article-link" data-v-7796d9ba="" href="https://www.betterhealth.vic.gov.au/health/conditionsandtreatments/first-aid-basics-and-drsabcd#bhc-content" style='background-color: transparent; text-decoration: underline; color: rgb(0, 128, 85); margin-left: 1rem; font-size: 0.875rem; line-height: 1.25rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400;'><span class="hide-mobile" data-v-7796d9ba="">Read the full fact sheet</span><svg aria-hidden="true" class="read-article-icon rpl-icon rpl-icon--arrow_down_primary" style="width:9.600000000000001px;height:10.4px;" data-v-7796d9ba="">
                                        <path d="M6.673 11.74l5-4.546a1.003 1.003 0 00.067-1.413 1.001 1.001 0 00-1.413-.066L7 8.739V1a1 1 0 10-2 0v7.739L1.673 5.715A1.001 1.001 0 000 6.454a1 1 0 00.327.74l5 4.546a1 1 0 001.346 0z"></path>
                                    </svg></a>
                            </div>
                            <ul class="content-intro__list" data-v-7796d9ba="" style='margin: 0px; padding-left: 1.1rem; font-size: 1rem; line-height: 1.375rem; font-family: VIC-Regular, Arial, Helvetica, "sans-serif"; font-weight: 400;'>
                                <li data-v-7796d9ba="">Some knowledge of basic first aid could mean the difference between life and death.</li>
                                <li data-v-7796d9ba="" style="margin-top: 1rem;">Consider doing a first aid course, so that you will be able to manage if someone is injured or becomes ill.</li>
                                <li data-v-7796d9ba="" style="margin-top: 1rem;">CPR is a life-saving skill that everyone should learn.</li>
                                <li data-v-7796d9ba="" style="margin-top: 1rem;">Keep a range of first aid kits handy at home, in the car and at work.</li>
                            </ul>
                        </div>
                        <div data-v-1e99a558="">
                            <div class="bhc-content" data-v-1e99a558="" style="margin-top: 3rem;">
                                <div class="rpl-anchor-links anchor-links" data-v-1e99a558="" style="padding-right: 0px; padding-left: 0px; position: relative; margin: 0px 0px 2.5rem;">
                                    <div class="rpl-anchor-links__row" style="max-width: none; margin: 0px;">
                                        <h2 class="rpl-anchor-links__title" style='margin: 0px; color: rgb(34, 34, 34); font-size: 1.125rem; line-height: 1.375rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400; padding-bottom: 0.5rem;'>On this page</h2>
                                    </div>
                                    <div class="rpl-anchor-links__row" style="max-width: none; margin: 0px;">
                                        <ul class="rpl-anchor-links__items" style="width: 698.656px; list-style: none; padding: 0px; margin: 0px;">
                                            <li class="rpl-anchor-links__item" style="margin: 1rem 0px; display: flex; -webkit-box-align: baseline; align-items: baseline;"><svg aria-hidden="true" class="rpl-icon rpl-icon--arrow_down_primary" style="width:9.600000000000001px;height:10.4px;">
                                                    <path d="M6.673 11.74l5-4.546a1.003 1.003 0 00.067-1.413 1.001 1.001 0 00-1.413-.066L7 8.739V1a1 1 0 10-2 0v7.739L1.673 5.715A1.001 1.001 0 000 6.454a1 1 0 00.327.74l5 4.546a1 1 0 001.346 0z"></path>
                                                </svg><a class="rpl-link rpl-text-link" data-print-url="#learn-the-first-aid-method-of-drsabcd" href="https://www.betterhealth.vic.gov.au/health/conditionsandtreatments/first-aid-basics-and-drsabcd#learn-the-first-aid-method-of-drsabcd" style='background-color: transparent; text-decoration: underline; -webkit-box-flex: 1; flex: 1 1 0%; display: block; color: rgb(0, 128, 85); font-size: 1.125rem; line-height: 1.375rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400;' target="">Learn the first aid method of DRSABCD</a></li>
                                            <li class="rpl-anchor-links__item" style="margin: 1rem 0px; display: flex; -webkit-box-align: baseline; align-items: baseline;"><svg aria-hidden="true" class="rpl-icon rpl-icon--arrow_down_primary" style="width:9.600000000000001px;height:10.4px;">
                                                    <path d="M6.673 11.74l5-4.546a1.003 1.003 0 00.067-1.413 1.001 1.001 0 00-1.413-.066L7 8.739V1a1 1 0 10-2 0v7.739L1.673 5.715A1.001 1.001 0 000 6.454a1 1 0 00.327.74l5 4.546a1 1 0 001.346 0z"></path>
                                                </svg><a class="rpl-link rpl-text-link" data-print-url="#where-to-learn-first-aid-and-cpr" href="https://www.betterhealth.vic.gov.au/health/conditionsandtreatments/first-aid-basics-and-drsabcd#where-to-learn-first-aid-and-cpr" style='background-color: transparent; text-decoration: underline; -webkit-box-flex: 1; flex: 1 1 0%; display: block; color: rgb(0, 128, 85); font-size: 1.125rem; line-height: 1.375rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400;' target="">Where to learn first aid and CPR</a></li>
                                            <li class="rpl-anchor-links__item" style="margin: 1rem 0px; display: flex; -webkit-box-align: baseline; align-items: baseline;"><svg aria-hidden="true" class="rpl-icon rpl-icon--arrow_down_primary" style="width:9.600000000000001px;height:10.4px;">
                                                    <path d="M6.673 11.74l5-4.546a1.003 1.003 0 00.067-1.413 1.001 1.001 0 00-1.413-.066L7 8.739V1a1 1 0 10-2 0v7.739L1.673 5.715A1.001 1.001 0 000 6.454a1 1 0 00.327.74l5 4.546a1 1 0 001.346 0z"></path>
                                                </svg><a class="rpl-link rpl-text-link" data-print-url="#infection-control-when-performing-cpr" href="https://www.betterhealth.vic.gov.au/health/conditionsandtreatments/first-aid-basics-and-drsabcd#infection-control-when-performing-cpr" style='background-color: transparent; text-decoration: underline; -webkit-box-flex: 1; flex: 1 1 0%; display: block; color: rgb(0, 128, 85); font-size: 1.125rem; line-height: 1.375rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400;' target="">Infection control when performing CPR</a></li>
                                            <li class="rpl-anchor-links__item" style="margin: 1rem 0px; display: flex; -webkit-box-align: baseline; align-items: baseline;"><svg aria-hidden="true" class="rpl-icon rpl-icon--arrow_down_primary" style="width:9.600000000000001px;height:10.4px;">
                                                    <path d="M6.673 11.74l5-4.546a1.003 1.003 0 00.067-1.413 1.001 1.001 0 00-1.413-.066L7 8.739V1a1 1 0 10-2 0v7.739L1.673 5.715A1.001 1.001 0 000 6.454a1 1 0 00.327.74l5 4.546a1 1 0 001.346 0z"></path>
                                                </svg><a class="rpl-link rpl-text-link" data-print-url="#first-aid-for-a-person-choking" href="https://www.betterhealth.vic.gov.au/health/conditionsandtreatments/first-aid-basics-and-drsabcd#first-aid-for-a-person-choking" style='background-color: transparent; text-decoration: underline; -webkit-box-flex: 1; flex: 1 1 0%; display: block; color: rgb(0, 128, 85); font-size: 1.125rem; line-height: 1.375rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400;' target="">First aid for a person choking</a></li>
                                            <li class="rpl-anchor-links__item" style="margin: 1rem 0px; display: flex; -webkit-box-align: baseline; align-items: baseline;"><svg aria-hidden="true" class="rpl-icon rpl-icon--arrow_down_primary" style="width:9.600000000000001px;height:10.4px;">
                                                    <path d="M6.673 11.74l5-4.546a1.003 1.003 0 00.067-1.413 1.001 1.001 0 00-1.413-.066L7 8.739V1a1 1 0 10-2 0v7.739L1.673 5.715A1.001 1.001 0 000 6.454a1 1 0 00.327.74l5 4.546a1 1 0 001.346 0z"></path>
                                                </svg><a class="rpl-link rpl-text-link" data-print-url="#first-aid-for-a-medication-or-drug-overdose" href="https://www.betterhealth.vic.gov.au/health/conditionsandtreatments/first-aid-basics-and-drsabcd#first-aid-for-a-medication-or-drug-overdose" style='background-color: transparent; text-decoration: underline; -webkit-box-flex: 1; flex: 1 1 0%; display: block; color: rgb(0, 128, 85); font-size: 1.125rem; line-height: 1.375rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400;' target="">First aid for a medication or drug overdose</a></li>
                                            <li class="rpl-anchor-links__item" style="margin: 1rem 0px; display: flex; -webkit-box-align: baseline; align-items: baseline;"><svg aria-hidden="true" class="rpl-icon rpl-icon--arrow_down_primary" style="width:9.600000000000001px;height:10.4px;">
                                                    <path d="M6.673 11.74l5-4.546a1.003 1.003 0 00.067-1.413 1.001 1.001 0 00-1.413-.066L7 8.739V1a1 1 0 10-2 0v7.739L1.673 5.715A1.001 1.001 0 000 6.454a1 1 0 00.327.74l5 4.546a1 1 0 001.346 0z"></path>
                                                </svg><a class="rpl-link rpl-text-link" data-print-url="#first-aid-kit" href="https://www.betterhealth.vic.gov.au/health/conditionsandtreatments/first-aid-basics-and-drsabcd#first-aid-kit" style='background-color: transparent; text-decoration: underline; -webkit-box-flex: 1; flex: 1 1 0%; display: block; color: rgb(0, 128, 85); font-size: 1.125rem; line-height: 1.375rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400;' target="">First aid kit</a></li>
                                            <li class="rpl-anchor-links__item" style="margin: 1rem 0px; display: flex; -webkit-box-align: baseline; align-items: baseline;"><svg aria-hidden="true" class="rpl-icon rpl-icon--arrow_down_primary" style="width:9.600000000000001px;height:10.4px;">
                                                    <path d="M6.673 11.74l5-4.546a1.003 1.003 0 00.067-1.413 1.001 1.001 0 00-1.413-.066L7 8.739V1a1 1 0 10-2 0v7.739L1.673 5.715A1.001 1.001 0 000 6.454a1 1 0 00.327.74l5 4.546a1 1 0 001.346 0z"></path>
                                                </svg><a class="rpl-link rpl-text-link" data-print-url="#reducing-the-risk-of-infected-wounds-during-first-aid" href="https://www.betterhealth.vic.gov.au/health/conditionsandtreatments/first-aid-basics-and-drsabcd#reducing-the-risk-of-infected-wounds-during-first-aid" style='background-color: transparent; text-decoration: underline; -webkit-box-flex: 1; flex: 1 1 0%; display: block; color: rgb(0, 128, 85); font-size: 1.125rem; line-height: 1.375rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400;' target="">Reducing the risk of infected wounds during first aid</a></li>
                                            <li class="rpl-anchor-links__item" style="margin: 1rem 0px; display: flex; -webkit-box-align: baseline; align-items: baseline;"><svg aria-hidden="true" class="rpl-icon rpl-icon--arrow_down_primary" style="width:9.600000000000001px;height:10.4px;">
                                                    <path d="M6.673 11.74l5-4.546a1.003 1.003 0 00.067-1.413 1.001 1.001 0 00-1.413-.066L7 8.739V1a1 1 0 10-2 0v7.739L1.673 5.715A1.001 1.001 0 000 6.454a1 1 0 00.327.74l5 4.546a1 1 0 001.346 0z"></path>
                                                </svg><a class="rpl-link rpl-text-link" data-print-url="#using-bandages-during-first-aid" href="https://www.betterhealth.vic.gov.au/health/conditionsandtreatments/first-aid-basics-and-drsabcd#using-bandages-during-first-aid" style='background-color: transparent; text-decoration: underline; -webkit-box-flex: 1; flex: 1 1 0%; display: block; color: rgb(0, 128, 85); font-size: 1.125rem; line-height: 1.375rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400;' target="">Using bandages during first aid</a></li>
                                            <li class="rpl-anchor-links__item" style="margin: 1rem 0px; display: flex; -webkit-box-align: baseline; align-items: baseline;"><svg aria-hidden="true" class="rpl-icon rpl-icon--arrow_down_primary" style="width:9.600000000000001px;height:10.4px;">
                                                    <path d="M6.673 11.74l5-4.546a1.003 1.003 0 00.067-1.413 1.001 1.001 0 00-1.413-.066L7 8.739V1a1 1 0 10-2 0v7.739L1.673 5.715A1.001 1.001 0 000 6.454a1 1 0 00.327.74l5 4.546a1 1 0 001.346 0z"></path>
                                                </svg><a class="rpl-link rpl-text-link" data-print-url="#where-to-get-help" href="https://www.betterhealth.vic.gov.au/health/conditionsandtreatments/first-aid-basics-and-drsabcd#where-to-get-help" style='background-color: transparent; text-decoration: underline; -webkit-box-flex: 1; flex: 1 1 0%; display: block; color: rgb(0, 128, 85); font-size: 1.125rem; line-height: 1.375rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400;' target="">Where to get help</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="bhc-content__components" data-v-1e99a558="">
                                    <div class="rpl-markup tide-wysiwyg app-wysiwyg bhc-content__component" data-v-1e99a558="" style='font-size: 1rem; line-height: 1.375rem; font-family: VIC-Regular, Arial, Helvetica, "sans-serif"; font-weight: 400; color: rgb(34, 34, 34);'>
                                        <div class="rpl-markup__inner" style="overflow-wrap: break-word;">
                                            <p style="max-width: 90%;">Learning basic first aid techniques can help you cope with an emergency. You may be able to keep a person breathing, reduce their pain or minimise the consequences of injury or sudden illness until an ambulance arrives. This could mean the difference between life and death for them.<br><br>It is a good idea to take a first aid course so that you can recognise an emergency and give basic first aid until professional help arrives.</p>
                                            <h2 style='margin-top: 3rem; color: rgb(0, 26, 53); margin-bottom: 1.75rem; font-size: 1.75rem; line-height: 2rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400; max-width: 37.875rem;'>Learn the first aid method of DRSABCD</h2>
                                            <p style="max-width: 90%;">First aid is as easy as ABC &ndash; airway, breathing and CPR (cardiopulmonary resuscitation). In any situation, apply the DRSABCD Action Plan.<br><br>DRSABCD stands for:</p>
                                            <ul style="padding-left: 1.1rem; margin: 1rem 0px 1.5rem; list-style-type: disc; max-width: 37.875rem;">
                                                <li style="padding-left: 0.25rem;"><strong style='font-weight: 400; font-family: VIC-SemiBold, Arial, Helvetica, "sans-serif"; font-size: 1rem; line-height: 1.5em;'>D</strong>anger &ndash; always check the danger to you, any bystanders and then the injured or ill person. Make sure you do not put yourself in danger when going to the assistance of another person.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;"><strong style='font-weight: 400; font-family: VIC-SemiBold, Arial, Helvetica, "sans-serif"; font-size: 1rem; line-height: 1.5em;'>R</strong>esponse &ndash; is the person conscious? Do they respond when you talk to them, touch their hands or squeeze their shoulder?</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;"><strong style='font-weight: 400; font-family: VIC-SemiBold, Arial, Helvetica, "sans-serif"; font-size: 1rem; line-height: 1.5em;'>S</strong>end for help &ndash; call triple zero (000). Don&rsquo;t forget to answer the questions asked by the operator.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;"><strong style='font-weight: 400; font-family: VIC-SemiBold, Arial, Helvetica, "sans-serif"; font-size: 1rem; line-height: 1.5em;'>A</strong>irway &ndash; Is the person&rsquo;s airway clear? Is the person breathing?</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">If the person is responding, they are conscious and their airway is clear, assess how you can help them with any injury.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">If the person is not responding and they are unconscious, you need to check their airway by opening their mouth and having a look inside. If their mouth is clear, tilt their head gently back (by lifting their chin) and check for breathing. If the mouth is not clear, place the person on their side, open their mouth and clear the contents, then tilt the head back and check for breathing.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;"><strong style='font-weight: 400; font-family: VIC-SemiBold, Arial, Helvetica, "sans-serif"; font-size: 1rem; line-height: 1.5em;'>B</strong>reathing &ndash; check for breathing by looking for chest movements (up and down). Listen by putting your ear near to their mouth and nose. Feel for breathing by putting your hand on the lower part of their chest. If the person is unconscious but breathing, turn them onto their side, carefully ensuring that you keep their head, neck and spine in alignment. Monitor their breathing until you hand over to the ambulance officers.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;"><strong style='font-weight: 400; font-family: VIC-SemiBold, Arial, Helvetica, "sans-serif"; font-size: 1rem; line-height: 1.5em;'>C</strong>PR (cardiopulmonary resuscitation) &ndash; if an adult is unconscious and not breathing, make sure they are flat on their back and then place the heel of one hand in the centre of their chest and your other hand on top. Press down firmly and smoothly (compressing to one third of their chest depth) 30 times. Give two breaths. To get the breath in, tilt their head back gently by lifting their chin. Pinch their nostrils closed, place your open mouth firmly over their open mouth and blow firmly into their mouth. Keep going with the 30 compressions and two breaths at the speed of approximately five repeats in two minutes until you hand over to the ambulance officers or another trained person, or until the person you are resuscitating responds. The method for CPR for children under eight and babies is very similar and you can learn these skills in a CPR course.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;"><strong style='font-weight: 400; font-family: VIC-SemiBold, Arial, Helvetica, "sans-serif"; font-size: 1rem; line-height: 1.5em;'>D</strong>efibrillator &ndash; for unconscious adults who are not breathing, apply an automated external defibrillator (AED) if one is available. They are available in many public places, clubs and organisations. An AED is a machine that delivers an electrical shock to cancel any irregular heart beat (arrhythmia), in an effort get the normal heart beating to re-establish itself. The devices are very simple to operate. Just follow the instructions and pictures on the machine, and on the package of the pads, as well as the voice prompts. If the person responds to defibrillation, turn them onto their side and tilt their head to maintain their airway. Some AEDs may not be suitable for children.</li>
                                            </ul>
                                            <h2 style='margin-top: 3rem; color: rgb(0, 26, 53); margin-bottom: 1.75rem; font-size: 1.75rem; line-height: 2rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400; max-width: 37.875rem;'>Where to learn first aid and CPR</h2>
                                            <p style="max-width: 90%;">You can attend a CPR training course or first aid course with a non-profit organisation such as St John Ambulance Australia (Victoria), Australian Red Cross and Life Saving Victoria. St John also runs awareness programs in schools and the community.<br><br>There is no age limit to learning CPR. The ability to carry out CPR is only limited by the physical capabilities of the person carrying out the procedure.<br><br>In some schools, CPR is a module of the first aid course taught to Year 9 students. CPR is a life skill that everyone should learn. Remember that doing some CPR in an emergency is better than doing nothing.</p>
                                            <h2 style='margin-top: 3rem; color: rgb(0, 26, 53); margin-bottom: 1.75rem; font-size: 1.75rem; line-height: 2rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400; max-width: 37.875rem;'>Infection control when performing CPR</h2>
                                            <p style="max-width: 90%;">To avoid contact with potentially infectious bodily fluids such as blood or saliva, everyone with training in resuscitation is advised to carry a resuscitation mask in their purse, wallet or first aid kit. This helps take the worry of infection out of helping someone in a life-threatening situation. These masks are available from first aid providers or from your pharmacy.</p>
                                            <h2 style='margin-top: 3rem; color: rgb(0, 26, 53); margin-bottom: 1.75rem; font-size: 1.75rem; line-height: 2rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400; max-width: 37.875rem;'>First aid for a person choking</h2>
                                            <p style="max-width: 90%;">Maintaining a clear airway is always the priority to make sure the person can keep breathing. You might need to roll them onto their side, but spinal injury is always a possibility in anyone involved in an accident. There are ways of placing an injured person on their side so that there is very little movement to their spine. You can learn these skills in a first aid course.</p>
                                            <h2 style='margin-top: 3rem; color: rgb(0, 26, 53); margin-bottom: 1.75rem; font-size: 1.75rem; line-height: 2rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400; max-width: 37.875rem;'>First aid for a medication or drug overdose</h2>
                                            <p style="max-width: 90%;">Medications are very unpredictable. Many medications or illicit drugs have dangerous side effects, particularly if they are mixed together or taken with alcohol.<br><br>If you are aware or suspect that someone you have found has overdosed on drugs or medications, do not leave them to &lsquo;sleep it off&rsquo;. A doctor or ambulance paramedic should assess any person who overdoses on any medication.<br><br>It is very important that you call triple zero (000) if you are aware or suspect that someone you have found has overdosed on drugs or medications, as many overdoses cause death.</p>
                                            <h2 style='margin-top: 3rem; color: rgb(0, 26, 53); margin-bottom: 1.75rem; font-size: 1.75rem; line-height: 2rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400; max-width: 37.875rem;'>First aid kit</h2>
                                            <p style="max-width: 90%;">As well as knowing some basic first aid techniques, it is important that households and workplaces have a first aid kit that meets their needs and is well organised, fully stocked and readily available at all times.<br><br>The contents should be appropriate to cope with a range of emergency situations, depending on the setting. It&rsquo;s a good idea to have a number of kits handy in different places, such as in the home, car or office.<br><br>First aid kits are available for purchase from a variety of providers, including St John Ambulance Australia (Victoria) or your local pharmacy. Specialty kits are also available to meet specific needs.</p>
                                            <h2 style='margin-top: 3rem; color: rgb(0, 26, 53); margin-bottom: 1.75rem; font-size: 1.75rem; line-height: 2rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400; max-width: 37.875rem;'>Reducing the risk of infected wounds during first aid</h2>
                                            <p style="max-width: 90%;">Open wounds are prone to infection. Suggestions to reduce the risk of infection include:</p>
                                            <ul style="padding-left: 1.1rem; margin: 1rem 0px 1.5rem; list-style-type: disc; max-width: 37.875rem;">
                                                <li style="padding-left: 0.25rem;">Wash your hands if possible before managing the wound. You could also use an antibacterial hand sanitiser.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">Put on the disposable gloves provided in your first aid kit.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">Try to avoid breathing or coughing over the wound.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">Cleaning of the wound depends on the type and severity of the wound, including the severity of the bleeding. You may just clean around the wound.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">Cover the wound with a sterile dressing. Try not to touch the dressing&rsquo;s surface before applying it to the wound.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">Seek medical advice or call triple zero (000) for an ambulance.</li>
                                            </ul>
                                            <p style="max-width: 90%;"><br>In an emergency, these suggestions may not be practical. If the injured person is bleeding heavily, don&rsquo;t waste time. For example, cleaning the wound might dislodge a blood clot and make the wound bleed again or bleed more.<br><br>Immediately apply pressure to a heavily bleeding wound (or around the wound if there is an embedded object), and apply a bandage when the bleeding has slowed down or stopped. Call triple zero (000) immediately.</p>
                                            <p style="max-width: 90%;"><br></p>
                                            <h2 style='margin-top: 3rem; color: rgb(0, 26, 53); margin-bottom: 1.75rem; font-size: 1.75rem; line-height: 2rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400; max-width: 37.875rem;'>Using bandages during first aid</h2>
                                            <p style="max-width: 90%;">This information is of a general nature only and should not be considered a replacement for proper first aid training.<br><br>General suggestions include:</p>
                                            <p style="max-width: 90%;"><br></p>
                                            <ul style="padding-left: 1.1rem; margin: 1rem 0px 1.5rem; list-style-type: disc; max-width: 37.875rem;">
                                                <li style="padding-left: 0.25rem;">The injured person should be sitting or lying down. Position yourself in front of the person on their injured side.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">Make sure their injured body part is supported in position before you start to bandage it.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">If the injured person can help by holding the padding in place, wrap the &lsquo;tail&rsquo; of the bandage one full turn around the limb, so that the bandage is anchored.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">If there is no assistance, wrap the &lsquo;tail&rsquo; of the bandage directly around the padding over the wound.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">Bandage up the limb, making sure each turn overlaps the turn before. Alternatively, you can bandage in a &lsquo;figure eight&rsquo; fashion.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">Make sure the bandage isn&rsquo;t too tight so you don&rsquo;t reduce blood flow to the extremities (hands and feet). Check by pressing on a fingernail or toenail of the injured limb &ndash; if the pink colour returns within a couple of seconds, the bandage isn&rsquo;t affecting the person&rsquo;s circulation. If the nail remains white for some time, loosen the bandage. Keep checking and adjusting the bandage, especially if swelling is a problem.</li>
                                            </ul>
                                            <h3 style='color: rgb(0, 26, 53); margin-bottom: 1.5rem; font-size: 1.5rem; line-height: 1.75rem; font-family: VIC-Bold, Arial, Helvetica, "sans-serif"; font-weight: 400; max-width: 37.875rem;'>Making an arm sling</h3>
                                            <p style="max-width: 90%;">After being bandaged, an injured forearm or wrist may require an arm sling to lift the arm and keep it from moving. Steps include:</p>
                                            <ul style="padding-left: 1.1rem; margin: 1rem 0px 1.5rem; list-style-type: disc; max-width: 37.875rem;">
                                                <li style="padding-left: 0.25rem;">Arrange the person&rsquo;s arm in a &lsquo;V&rsquo; so that it is held in front of their body and bent at the elbow, with the hand resting in the hollow where the collarbone meets the shoulder.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">Open a triangular bandage and place it on top of the injured arm. The longest edge needs to be lengthwise along the person&rsquo;s body and the point of the bandage should be towards the person&rsquo;s elbow on their injured side. You only need enough material to tie a knot at the fingertip end.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">Create a cradle (hammock) around the injured arm by folding the upper half of the long edge under the injured arm.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">Gently gather the material together at the elbow and pull it tight without pulling the bandage off the injured arm. Twist the material into a long spiral.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">Bring the long spiral around and then up the person&rsquo;s back.</li>
                                                <li style="padding-left: 0.25rem; margin-top: 0.5rem;">Tie the two ends together firmly at the person&rsquo;s fingertips.</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>''',
        ),
      ),
    );
  }
}
